#!/usr/bin/env python3
"""
Converts the first N trackpoints of a GPX file into a C array matching
sLocationData's fields (lat, lon, alt, speed, course, utc_time, date), for
stravaV11_fw's GPS simulation feature. Speed/course are computed once here
(great-circle distance/bearing between consecutive points), not on-device,
per the user's explicit choice -- keeps the device-side replay loop to a
simple array lookup.
"""
import sys
import math
import xml.etree.ElementTree as ET
from datetime import datetime, timezone

NS = {"g": "http://www.topografix.com/GPX/1/1"}


def haversine_m(lat1, lon1, lat2, lon2):
    R = 6371008.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dlambda / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


def bearing_deg(lat1, lon1, lat2, lon2):
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dlambda = math.radians(lon2 - lon1)
    x = math.sin(dlambda) * math.cos(p2)
    y = math.cos(p1) * math.sin(p2) - math.sin(p1) * math.cos(p2) * math.cos(dlambda)
    return (math.degrees(math.atan2(x, y)) + 360.0) % 360.0


def main():
    gpx_path, n_points, out_path = sys.argv[1], int(sys.argv[2]), sys.argv[3]

    tree = ET.parse(gpx_path)
    root = tree.getroot()
    trkpts = root.findall(".//g:trkpt", NS)[:n_points]

    points = []
    for pt in trkpts:
        lat = float(pt.get("lat"))
        lon = float(pt.get("lon"))
        ele_el = pt.find("g:ele", NS)
        ele = float(ele_el.text) if ele_el is not None else 0.0
        time_el = pt.find("g:time", NS)
        t = datetime.strptime(time_el.text, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        points.append((lat, lon, ele, t))

    rows = []
    for i, (lat, lon, ele, t) in enumerate(points):
        if i == 0:
            speed_kmh = 0.0
            course = 0.0
        else:
            plat, plon, _, pt_time = points[i - 1]
            dt = (t - pt_time).total_seconds()
            dist_m = haversine_m(plat, plon, lat, lon)
            speed_kmh = (dist_m / dt) * 3.6 if dt > 0 else 0.0
            course = bearing_deg(plat, plon, lat, lon)

        utc_time = t.hour * 3600 + t.minute * 60 + t.second
        date = (t.year % 100) + t.day * 10000 + t.month * 100

        rows.append((lat, lon, ele, speed_kmh, course, utc_time, date))

    with open(out_path, "w") as f:
        f.write("/* Auto-generated by gpx_to_c.py -- do not hand-edit.\n")
        f.write(f" * Source: {gpx_path} (first {len(rows)} trackpoints)\n")
        f.write(" * Fields match sLocationData: lat, lon, alt (m), speed (km/h),\n")
        f.write(" * course (deg), utc_time (sec since midnight UTC), date (encoded\n")
        f.write(" * as Locator.cpp's own (year%100) + day*10000 + month*100).\n")
        f.write(" * speed/course are pre-computed here (great-circle distance/bearing\n")
        f.write(" * between consecutive points), not on-device.\n")
        f.write(" */\n\n")
        f.write("#ifndef GPS_SIM_ROUTE_H_\n#define GPS_SIM_ROUTE_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("struct gps_sim_point {\n")
        f.write("\tfloat lat;\n\tfloat lon;\n\tfloat alt;\n\tfloat speed;\n\tfloat course;\n")
        f.write("\tuint32_t utc_time;\n\tuint32_t date;\n")
        f.write("};\n\n")
        f.write(f"#define GPS_SIM_ROUTE_LEN {len(rows)}\n\n")
        f.write("static const struct gps_sim_point gps_sim_route[GPS_SIM_ROUTE_LEN] = {\n")
        for lat, lon, ele, speed, course, utc_time, date in rows:
            f.write(
                f"\t{{ {lat:.7f}f, {lon:.7f}f, {ele:.1f}f, {speed:.3f}f, {course:.2f}f, "
                f"{utc_time}u, {date}u }},\n"
            )
        f.write("};\n\n")
        f.write("#endif /* GPS_SIM_ROUTE_H_ */\n")

    print(f"Wrote {len(rows)} points to {out_path}")
    print(f"First point: {rows[0]}")
    print(f"Last point:  {rows[-1]}")
    total_dist = sum(
        haversine_m(rows[i - 1][0], rows[i - 1][1], rows[i][0], rows[i][1])
        for i in range(1, len(rows))
    )
    print(f"Total distance over {len(rows)} points: {total_dist:.1f} m")
    print(f"Avg speed: {sum(r[3] for r in rows) / len(rows):.1f} km/h")


if __name__ == "__main__":
    main()
