#!/usr/bin/env python3
"""
Converts a directory of tools/osm_to_tiles.py-generated tile_<lat>_<lon>.bin
files into an embeddable C header -- the only way to get real map data
onto the device's SD card right now, since USB MSC isn't wired up in
this port yet (Phase 9's known gap) and there's no other file-transfer
path. The firmware seeds these bytes onto the card at boot via
fs_write(), same pattern as test_tile_data.h's synthetic fixture.

Emits, for each tile, a `static const uint8_t <c_name>[] = {...};` array
plus a lookup table `static const struct embedded_tile embedded_tiles[]`
(filename, pointer, length) so the firmware can seed all of them in a
loop rather than needing one fs_write() call per file hand-written here.

Usage: python3 tile_to_c.py <tiles_dir> <output.h> [--var-prefix NAME]
"""
import argparse
import os
import re


def c_name_for(filename, prefix):
    stem = os.path.splitext(filename)[0]
    safe = re.sub(r"[^0-9A-Za-z_]", "_", stem)
    return f"{prefix}_{safe}"


def emit_array(f, c_name, data):
    f.write(f"static const uint8_t {c_name}[] = {{\n")
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        f.write("\t" + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    f.write("};\n\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("tiles_dir", help="directory of tile_<lat>_<lon>.bin files")
    parser.add_argument("output_h", help="output C header path")
    parser.add_argument("--var-prefix", default="embedded_tile",
                         help="C identifier prefix for each tile's array (default: embedded_tile)")
    args = parser.parse_args()

    tile_files = sorted(f for f in os.listdir(args.tiles_dir) if f.endswith(".bin"))
    if not tile_files:
        parser.error(f"no .bin files found in {args.tiles_dir}")

    guard = os.path.splitext(os.path.basename(args.output_h))[0].upper() + "_H_"

    with open(args.output_h, "w") as f:
        f.write(f"/* Auto-generated by tools/tile_to_c.py from {len(tile_files)} real\n")
        f.write(f" * tools/osm_to_tiles.py tile file(s) in {args.tiles_dir} -- do not hand-edit.\n")
        f.write(" */\n\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write("#include <stddef.h>\n#include <stdint.h>\n\n")

        entries = []
        total_bytes = 0
        for filename in tile_files:
            path = os.path.join(args.tiles_dir, filename)
            with open(path, "rb") as tf:
                data = tf.read()
            c_name = c_name_for(filename, args.var_prefix)
            emit_array(f, c_name, data)
            entries.append((filename, c_name, len(data)))
            total_bytes += len(data)

        f.write("struct embedded_tile {\n")
        f.write("\tconst char *name;\n")
        f.write("\tconst uint8_t *data;\n")
        f.write("\tsize_t len;\n")
        f.write("};\n\n")

        f.write(f"#define EMBEDDED_TILE_COUNT {len(entries)}\n\n")
        f.write("static const struct embedded_tile embedded_tiles[EMBEDDED_TILE_COUNT] = {\n")
        for filename, c_name, length in entries:
            f.write(f'\t{{ "{filename}", {c_name}, sizeof({c_name}) }},\n')
        f.write("};\n\n")

        f.write(f"#endif /* {guard} */\n")

    print(f"Wrote {len(entries)} tiles ({total_bytes} bytes total) to {args.output_h}")
    for filename, c_name, length in entries:
        print(f"  {filename}: {length} bytes -> {c_name}")


if __name__ == "__main__":
    main()
